In [1]:
import tensorflow as tf

gpus = tf.config.list_physical_devices('GPU')
if gpus:
    try:
        for gpu in gpus:
            tf.config.experimental.set_memory_growth(gpu, True)
        print("Memory growth enabled")
    except Exception as e:
        print("Could not set memory growth:", e)

print(tf.config.list_physical_devices('GPU'))


2026-01-15 04:28:58.200676: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2026-01-15 04:28:58.242492: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2026-01-15 04:28:59.299769: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.


Memory growth enabled
[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


In [2]:
# # 작은 행렬곱을 GPU로 실행 시도
# if gpus:
#     with tf.device('/GPU:0'):
#         a = tf.random.normal([4096, 4096])
#         b = tf.random.normal([4096, 4096])
#         c = tf.matmul(a, b)
#     print("matmul done. shape:", c.shape)
# else:
#     print("No GPU detected by TF")

In [3]:
x = tf.constant([1,2])
x_var = tf.Variable(x, name ='var1')
with tf.device('GPU:0'):
    x_1 = tf.constant([1,3,4])
    x_2 = tf.constant([1])
    x_3 = x_1 + x_2
display(x_1, x_1.device)
display(x_2, x_2.device)
display(x_3, x_3.device)


I0000 00:00:1768418939.878955   14396 gpu_device.cc:2020] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 5560 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 4060 Laptop GPU, pci bus id: 0000:01:00.0, compute capability: 8.9


<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 3, 4], dtype=int32)>

'/job:localhost/replica:0/task:0/device:GPU:0'

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([1], dtype=int32)>

'/job:localhost/replica:0/task:0/device:GPU:0'

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 4, 5], dtype=int32)>

'/job:localhost/replica:0/task:0/device:GPU:0'